### ISSUE TITLE
After updating a user's information, the returned user in response is still the old user

### ISSUE THREAD

**Issue by ZhijieZheng-UM** [Aiphox/DogDates#63]
The updated new dogName should be Sun but receive the old dogName Snow.
![image](https://user-images.githubusercontent.com/92958353/157076764-3a206e07-afbf-4a11-84ad-d1a05fb2f57e.png)

**Comment by sammulto** [comment]
fixed in https://github.com/Aiphox/DogDates/commit/e8b784514bfc3b3d34c180eb50e9d6e0a15c24e5
